### ISSUE TITLE
Python translation

### ISSUE THREAD

**Issue by missing-semi-colon** [paulguy/gmmkctl#3]
Hello, firstly thanks for making this tool, it's very useful.

I have translated this project into Python here: https://github.com/missing-semi-colon/gmmkctl_py. Is this ok with you? I have given credit in the README, but if you would like me to do anything else please let me know. Also, may you consider giving a license to this project (maybe MIT or GPL)?

Also, if there is anything useful in my project feel free to use it in this one.

Many thanks.

**Comment by paulguy** [comment]
Oh yeah you're right i never did add a license.  Well, that's hopefully settled now.  Yours looks fine.  I haven't tested it but yeah python is probably the more interoperable language, where mine might be somewhat linux-specific.
