### ISSUE TITLE
doesn't work with GMMK Compact

### ISSUE THREAD

**Issue by jrwren** [paulguy/gmmkctl#4]
I updated source with:
+#define GMMK_VENDOR_ID  (12815)
+#define GMMK_PRODUCT_ID (20580)

which I found in output of `ioreg -p IOUSB  -w0 -l` on macos.

model on bottom of kb is GMMK-COM-BRN-W

Maybe this is a different GMMK that isn't compatible?

**Comment by paulguy** [comment]
I've only developed this for/tested against the original full size GMMK purchased many years ago with USB VID 0c45 PID 652f, and all the development was done pretty much when this was their only product line.  I don't have any of the other varieties, and it's also possible there have been revisions between then and now.  Unfortunately, as I don't have that hardware, I can't develop an update for supporting it nor determining how different their protocol may be.  Also, never tested on macOS, only on Linux.

**Comment by paulguy** [comment]
Probably should close this, since I can't add this functionality/fix the problem.
